env:
  contexts:
    - name: default
      urls: [http://localhost:5173/]
      excludePaths:
        - http://localhost:5173/[A-Za-z0-9]+
  parameters:
    progressToStdout: true
jobs:
  - type: script
    parameters:
      action: add
      name: http-sender
      type: httpsender
      engine: jython
      file: http-sender.py
  - type: script
    parameters:
      action: enable
      name: http-sender
  - type: alertFilter
    alertFilters:
      - ruleId: 10038
        newRisk: 'False Positive'
      - ruleId: 6
        newRisk: 'False Positive'
      - ruleId: 10202
        newRisk: 'False Positive'
      - ruleId: 20016
        newRisk: 'False Positive'
      - ruleId: 10202
        newRisk: 'False Positive'
      - ruleId: 10020
        newRisk: 'False Positive'
      - ruleId: 10202
        newRisk: 'False Positive'
      - ruleId: 10098
        newRisk: 'False Positive'
  - type: spider
    parameters:
      maxDepth: 3
  - type: spiderAjax
    parameters:
      maxDuration: 1
      maxCrawlDepth: 3
  - type: activeScan
    parameters:
      maxScanDurationInMins: 2
  - type: report
    parameters:
      reportFile: report_html.html
    risks:
      - high
      - medium
      - low
      - info
    confidences:
      - high
      - medium
      - low
  - type: report
    parameters:
      template: traditional-json
      reportFile: report_json.json
    risks:
      - high
      - medium
    confidences:
      - high
      - medium
      - low
