name: NPM audit

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install deps
      run: npm ci
      
    - name: NPM Audit with ignore list
      uses: solita-miikkakiv/actions/shell-actions/npm-audit-improved@main
        
