name: Build and scan

on:
  workflow_dispatch:

  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: zap-testing
        
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install deps
      run: npm ci
      
    - name: Run app
      run: |
        npm run dev &
    
    - name: Wait until app is running
      run: |
        for attempt in {1..60}; do sleep 1; if curl -s http://localhost:5173; then echo "App started"; break; fi; echo "Waiting for app to start.."; done

    - name: ZAP Docker scan
      uses: solita-miikkakiv/actions/shell-actions/vuln-scan-docker@main
      with:
        test_user: ${{ secrets.TEST_USER }}
        test_password: ${{ secrets.TEST_PASSWORD }}
        zap_configfile: .zap/config.yaml
        
